<?php

use Illuminate\Database\Seeder;
use App\Advertisement;
use App\User;

class AdvertisementTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // 1
        $ad = new Advertisement();
        $ad->name = "Arthur's Air Conditioning";
        $ad->service = "Air Conditioning";
        $ad->quote = 50;
        $ad->body = "We provide the best air to your house.";
        $ad->user_id = User::where('name', 'Arthur Curry')->value('id');
        $ad->town = "Melton";
        $ad->postcode = 3337;
        $ad->phone = "0400000001";
        $ad->email = User::where('name', 'Arthur Curry')->value('email');
        $ad->max_dist = 30;
        $ad->latitude = '-37.669142';
        $ad->longitude = '144.543721';
        $ad->save();
        // 2
        $ad = new Advertisement();
        $ad->name = 'Waynes Industries';
        $ad->service = "Electricians";
        $ad->quote = 50;
        $ad->body = "No more faulty wires if you call me";
        $ad->user_id = User::where('name', 'Bruce Wayne')->value('id');
        $ad->town = "Taylors Lakes";
        $ad->postcode = 3038;
        $ad->phone = "0400000002";
        $ad->email = User::where('name', 'Bruce Wayne')->value('email');
        $ad->max_dist = 25;
        $ad->latitude = '-37.701944';
        $ad->longitude = '144.79715';
        $ad->save();
        // 3
        $ad = new Advertisement();
        $ad->name = "Cain's Drains";
        $ad->service = "Drains";
        $ad->quote = 100;
        $ad->body = "Leaky drain, come sya hi to Cain";
        $ad->user_id = User::where('name', 'Cassandra Cain')->value('id');
        $ad->town = "Taylors Lakes";
        $ad->postcode = 3038;
        $ad->phone = "0400000003";
        $ad->email = User::where('name', 'Cassandra Cain')->value('email');
        $ad->max_dist = 25;
        $ad->latitude = '-37.701944';
        $ad->longitude = '144.79715';
        $ad->save();
        // 4
        $ad = new Advertisement();
        $ad->name = "Lance's Fences";
        $ad->service = "Fencing";
        $ad->quote = 50;
        $ad->body = "Give us a call between 12pm and 3pm for a free quote";
        $ad->user_id = User::where('name', 'Dinah Lance')->value('id');
        $ad->town = "Sunbury";
        $ad->postcode = 3429;
        $ad->phone = "0400000004";
        $ad->email = User::where('name', 'Dinah Lance')->value('email');
        $ad->max_dist = 50;
        $ad->latitude = '-37.5794919';
        $ad->longitude = '144.7288981';
        $ad->save();
        // 5
        $ad = new Advertisement();
        $ad->name = "Thrawne's Fencing";
        $ad->service = "Fencing";
        $ad->quote = 50;
        $ad->body = "No fence big or small we cannot handle";
        $ad->user_id = User::where('name', 'Eobard Thrawne')->value('id');
        $ad->town = "Reservoir";
        $ad->postcode = 3073;
        $ad->phone = "0400000005";
        $ad->email = User::where('name', 'Eobard Thrawne')->value('email');
        $ad->max_dist = 20;
        $ad->latitude = '-37.714286';
        $ad->longitude = '145.007847';
        $ad->save();
        // 6
        $ad = new Advertisement();
        $ad->name = "Smoke's Fireplaces";
        $ad->service = "Fireplaces";
        $ad->quote = 0;
        $ad->body = "No more being cold in winter, give us a call and we can set you up with a firey fireplace.";
        $ad->user_id = User::where('name', 'Felicity Smoke')->value('id');
        $ad->town = "Essendon";
        $ad->postcode = 3040;
        $ad->phone = "0400000006";
        $ad->email = User::where('name', 'Felicity Smoke')->value('email');
        $ad->max_dist = 40;
        $ad->latitude = '--37.755337';
        $ad->longitude = '144.917282';
        $ad->save();
        // 7
        $ad = new Advertisement();
        $ad->name = "Guy Gardner's Gardens";
        $ad->service = "Gardeners";
        $ad->quote = 150;
        $ad->body = "My people will keep your gardens nice and neat";
        $ad->user_id = User::where('name', 'Guy Gardner')->value('id'); 
        $ad->town = "Pascoe Vale";
        $ad->postcode = 3044;
        $ad->phone = "0400000007";
        $ad->email = User::where('name', 'Guy Gardner')->value('email');
        $ad->max_dist = 30;
        $ad->latitude = '-37.730366';
        $ad->longitude = '144.92868';
        $ad->save();
        // 8
        $ad = new Advertisement();
        $ad->name = "Hal's Carpentry";
        $ad->service = "Decking";
        $ad->quote = 0;
        $ad->body = "Need a wooden structure up, I can help";
        $ad->user_id = User::where('name', 'Hal Jordan')->value('id');  
        $ad->town = "Sunshine";
        $ad->postcode = 3020;
        $ad->phone = "0400000008";
        $ad->email = User::where('name', 'Hal Jordan')->value('email');
        $ad->max_dist = 30;
        $ad->latitude = '-37.786461';
        $ad->longitude = '144.83194';
        $ad->save();
        // 9
        $ad = new Advertisement();
        $ad->name = "Hal's Carpentry";
        $ad->service = "Carpenters";
        $ad->quote = 0;
        $ad->body = "Need a wooden structure up, I can help";
        $ad->user_id = User::where('name', 'Hal Jordan')->value('id'); 
        $ad->town = "Sunshine";
        $ad->postcode = 3020;
        $ad->phone = "0400000008";
        $ad->email = User::where('name', 'Hal Jordan')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.786461';
        $ad->longitude = '144.83194';
        $ad->save();
        // 10
        $ad = new Advertisement();
        $ad->name = "Hal's Carpentry";
        $ad->service = "Gazebo";
        $ad->quote = 0;
        $ad->body = "Need a wooden structure up, I can help";
        $ad->user_id = User::where('name', 'Hal Jordan')->value('id');
        $ad->town = "Sunshine";
        $ad->postcode = 3020;
        $ad->phone = "0400000008";
        $ad->email = User::where('name', 'Hal Jordan')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.786461';
        $ad->longitude = '144.83194';
        $ad->save();
        // 11
        $ad = new Advertisement();
        $ad->name = "Hal's Carpentry";
        $ad->service = "Patios";
        $ad->quote = 0;
        $ad->body = "Need a wooden structure up, I can help";
        $ad->user_id = User::where('name', 'Hal Jordan')->value('id');
        $ad->town = "Sunshine";
        $ad->postcode = 3020;
        $ad->phone = "0400000008";
        $ad->email = User::where('name', 'Hal Jordan')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.786461';
        $ad->longitude = '144.83194';
        $ad->save();
        // 12
        $ad = new Advertisement();
        $ad->name = "Hal's Carpentry";
        $ad->service = "Pergolas";
        $ad->quote = 0;
        $ad->body = "Need a wooden structure up, I can help";
        $ad->user_id = User::where('name', 'Hal Jordan')->value('id');
        $ad->town = "Sunshine";
        $ad->postcode = 3020;
        $ad->phone = "0400000008";
        $ad->email = User::where('name', 'Hal Jordan')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.786461';
        $ad->longitude = '144.83194';
        $ad->save();
        // 13
        $ad = new Advertisement();
        $ad->name = "West Concreting";
        $ad->service = "Paving";
        $ad->quote = 80;
        $ad->body = "Any concreting needs, concreint, paving, slabs, rendering";
        $ad->user_id = User::where('name', 'Iris West')->value('id');
        $ad->town = "St Albans";
        $ad->postcode = 3021;
        $ad->phone = "0400000009";
        $ad->email = User::where('name', 'Iris West')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.736111';
        $ad->longitude = '144.803889';
        $ad->save();
        // 14
        $ad = new Advertisement();
        $ad->name = "West Concreting";
        $ad->service = "Concreting";
        $ad->quote = 0;
        $ad->body = "Any concreting needs, concreint, paving, slabs, rendering";
        $ad->user_id = User::where('name', 'Iris West')->value('id');
        $ad->town = "St Albans";
        $ad->postcode = 3021;
        $ad->phone = "0400000009";
        $ad->email = User::where('name', 'Iris West')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.736111';
        $ad->longitude = '144.803889';
        $ad->save();
        // 15
        $ad = new Advertisement();
        $ad->name = "West Concreting";
        $ad->service = "Rendering";
        $ad->quote = 0;
        $ad->body = "Any concreting needs, concreint, paving, slabs, rendering";
        $ad->user_id = User::where('name', 'Iris West')->value('id');
        $ad->town = "St Albans";
        $ad->postcode = 3021;
        $ad->phone = "0400000009";
        $ad->email = User::where('name', 'Iris West')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.736111';
        $ad->longitude = '144.803889';
        $ad->save();
        // 16
        $ad = new Advertisement();
        $ad->name = "Todd's Concreting";
        $ad->service = "Concreting";
        $ad->quote = 0;
        $ad->body = "We do drive ways, footpaths, sheds, and house slabs.";
        $ad->user_id = User::where('name', 'Jason Todd')->value('id');
        $ad->town = "Blackburn";
        $ad->postcode = 3130;
        $ad->phone = "0400000010";
        $ad->email = User::where('name', 'Jason Todd')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.819464';
        $ad->longitude = '145.153407';
        $ad->save();
        // 17
        $ad = new Advertisement();
        $ad->name = "Rayner's wiring";
        $ad->service = "Electricians";
        $ad->quote = 100;
        $ad->body = "We can wiring anything up in your house";
        $ad->user_id = User::where('name', 'Kyle Rayner')->value('id');
        $ad->town = "Glen Iris";
        $ad->postcode = 3146;
        $ad->phone = "0400000011";
        $ad->email = User::where('name', 'Kyle Rayner')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.860009';
        $ad->longitude = '145.057356';
        $ad->save();
        // 18
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Electricians";
        $ad->quote = 0;
        $ad->body = "Making a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id');
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 19
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Gardeners";
        $ad->quote = 0;
        $ad->body = "Making a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id'); 
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 20
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Plumbing";
        $ad->quote = 0;
        $ad->body = "Making a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id'); 
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 21
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Fencing";
        $ad->quote = 0;
        $ad->body = "Making a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id');
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 22
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Drains";
        $ad->quote = 0;
        $ad->body = "Making a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id');
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 23
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Concreting";
        $ad->quote = 0;
        $ad->body = "Making a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id'); 
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 24
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Carpenters";
        $ad->quote = 0;
        $ad->body = "Making a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id');
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 25
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Builders";
        $ad->quote = 0;
        $ad->body = "Makign a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id');
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 26
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Bricklayers";
        $ad->quote = 0;
        $ad->body = "Makign a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id'); 
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 27
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Windows";
        $ad->quote = 0;
        $ad->body = "Makign a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id');
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 28
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Heating";
        $ad->quote = 0;
        $ad->body = "Makign a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id'); 
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 29
        $ad = new Advertisement();
        $ad->name = "LEX Corp";
        $ad->service = "Roofing";
        $ad->quote = 0;
        $ad->body = "Makign a better world";
        $ad->user_id = User::where('name', 'Lex Luthor')->value('id'); 
        $ad->town = "South Bank";
        $ad->postcode = 3006;
        $ad->phone = "0400000012";
        $ad->email = User::where('name', 'Lex Luthor')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.829';
        $ad->longitude = '144.957';
        $ad->save();
        // 30
        $ad = new Advertisement();
        $ad->name = "Merlyn Global Group";
        $ad->service = "Architects";
        $ad->quote = 0;
        $ad->body = "Best builders in town";
        $ad->user_id = User::where('name', 'Malcolm Merlyn')->value('id'); 
        $ad->town = "Carlton";
        $ad->postcode = 3053;
        $ad->phone = "0400000013";
        $ad->email = User::where('name', 'Malcolm Merlyn')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.801047';
        $ad->longitude = '144.969861';
        $ad->save();
        // 31
        $ad = new Advertisement();
        $ad->name = "Merlyn Global Group";
        $ad->service = "Builders";
        $ad->quote = 0;
        $ad->body = "Best builders in town";
        $ad->user_id = User::where('name', 'Malcolm Merlyn')->value('id');  
        $ad->town = "Carlton";
        $ad->postcode = 3053;
        $ad->phone = "0400000013";
        $ad->email = User::where('name', 'Malcolm Merlyn')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.801047';
        $ad->longitude = '144.969861';
        $ad->save();
        // 32
        $ad = new Advertisement();
        $ad->name = "Merlyn Global Group";
        $ad->service = "Demolition";
        $ad->quote = 0;
        $ad->body = "Best builders in town";
        $ad->user_id = User::where('name', 'Malcolm Merlyn')->value('id'); 
        $ad->town = "Carlton";
        $ad->postcode = 3053;
        $ad->phone = "0400000013";
        $ad->email = User::where('name', 'Malcolm Merlyn')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.801047';
        $ad->longitude = '144.969861';
        $ad->save();
        // 33
        $ad = new Advertisement();
        $ad->name = "Merlyn Global Group";
        $ad->service = "Excavation";
        $ad->quote = 0;
        $ad->body = "Best builders in town";
        $ad->user_id = User::where('name', 'Malcolm Merlyn')->value('id'); 
        $ad->town = "Carlton";
        $ad->postcode = 3053;
        $ad->phone = "0400000013";
        $ad->email = User::where('name', 'Malcolm Merlyn')->value('email');
        $ad->max_dist = 30; 
        $ad->latitude = '-37.801047';
        $ad->longitude = '144.969861';
        $ad->save();
        // 34
        $ad = new Advertisement();
        $ad->name = "Fury Heating";
        $ad->service = "Heaters";
        $ad->quote = 50;
        $ad->body = "We keep you warm over the winter";
        $ad->user_id = User::where('name', 'Nick Fury')->value('id'); 
        $ad->town = "Brunswick";
        $ad->postcode = 3056;
        $ad->phone = "0400000014";
        $ad->email = User::where('name', 'Nick Fury')->value('email');
        $ad->max_dist = 35; 
        $ad->latitude = '-37.767872';
        $ad->longitude = '144.961929';
        $ad->save();
        // 35
        $ad = new Advertisement();
        $ad->name = "Fury Heating";
        $ad->service = "Heating Systems";
        $ad->quote = 50;
        $ad->body = "We keep you warm over the winter";
        $ad->user_id = User::where('name', 'Nick Fury')->value('id'); 
        $ad->town = "Brunswick";
        $ad->postcode = 3056;
        $ad->phone = "0400000014";
        $ad->email = User::where('name', 'Nick Fury')->value('email');
        $ad->max_dist = 35; 
        $ad->latitude = '-37.767872';
        $ad->longitude = '144.961929';
        $ad->save();
        // 36
        $ad = new Advertisement();
        $ad->name = "Fury Heating";
        $ad->service = "Underfloor Heating Systems";
        $ad->quote = 50;
        $ad->body = "We keep you warm over the winter";
        $ad->user_id = User::where('name', 'Nick Fury')->value('id'); 
        $ad->town = "Brunswick";
        $ad->postcode = 3056;
        $ad->phone = "0400000014";
        $ad->email = User::where('name', 'Nick Fury')->value('email');
        $ad->max_dist = 35; 
        $ad->latitude = '-37.767872';
        $ad->longitude = '144.961929';
        $ad->save();
        // 37
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Architects";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');  
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 38
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Bricklayers";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 39
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Builders";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 40
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Carpenters";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 41
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Carpet Layers";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 42
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Carports";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 43
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Concreting";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 44
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Decking";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 45
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Doors";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 46
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Drains";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 47
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Electricians";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 48
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Excavation";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 49
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Fencing";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 50 
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Garages";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 51
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Gas Fitters";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');  
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 52
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Home Security";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 53
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Insulation";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 54
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Kitchens";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 55
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Landscapers";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 56
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Lawn Mowing";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 57
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Lighting";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 58
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Locksmith";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 59
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Painters";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 60
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Pavers";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');  
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 61
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Plastering";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 62
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Plumbing";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id'); 
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 63
        $ad = new Advertisement();
        $ad->name = "Queen Industries";
        $ad->service = "Roofing";
        $ad->quote = 0;
        $ad->body = "Moving the world into the future";
        $ad->user_id = User::where('name', 'Oliver Queen')->value('id');
        $ad->town = "Richmond";
        $ad->postcode = 3121;
        $ad->phone = "0400000015";
        $ad->email = User::where('name', 'Oliver Queen')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.818635';
        $ad->longitude = '145.00147';
        $ad->save();
        // 64
        $ad = new Advertisement();
        $ad->name = "Parker Gardens";
        $ad->service = "Lanscapers";
        $ad->quote = 50;
        $ad->body = "Who doesn't like a good park";
        $ad->user_id = User::where('name', 'Peter Parker')->value('id'); 
        $ad->town = "Thornbury";
        $ad->postcode = 3071;
        $ad->phone = "0400000016";
        $ad->email = User::where('name', 'Peter Parker')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.76';
        $ad->longitude = '145.007';
        $ad->save();
        // 65
        $ad = new Advertisement();
        $ad->name = "Parker Gardens";
        $ad->service = "Gardeners";
        $ad->quote = 50;
        $ad->body = "Who doesn't like a good park";
        $ad->user_id = User::where('name', 'Peter Parker')->value('id'); 
        $ad->town = "Thornbury";
        $ad->postcode = 3071;
        $ad->phone = "0400000016";
        $ad->email = User::where('name', 'Peter Parker')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.76';
        $ad->longitude = '145.007';
        $ad->save();
        // 66
        $ad = new Advertisement();
        $ad->name = "Parker Gardens";
        $ad->service = "Architects";
        $ad->quote = 50;
        $ad->body = "Who doesn't like a good park";
        $ad->user_id = User::where('name', 'Peter Parker')->value('id'); 
        $ad->town = "Thornbury";
        $ad->postcode = 3071;
        $ad->phone = "0400000016";
        $ad->email = User::where('name', 'Peter Parker')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.76';
        $ad->longitude = '145.007';
        $ad->save();
        // 67
        $ad = new Advertisement();
        $ad->name = "Parker Gardens";
        $ad->service = "Lawn & Turf";
        $ad->quote = 50;
        $ad->body = "Who doesn't like a good park";
        $ad->user_id = User::where('name', 'Peter Parker')->value('id');
        $ad->town = "Thornbury";
        $ad->phone = "0400000016";
        $ad->email = User::where('name', 'Peter Parker')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.76';
        $ad->longitude = '145.007';
        $ad->save();
        // 68
        $ad = new Advertisement();
        $ad->name = "Parker Gardens";
        $ad->service = "Lawn Mowing";
        $ad->quote = 50;
        $ad->body = "Who doesn't like a good park";
        $ad->user_id = User::where('name', 'Peter Parker')->value('id');
        $ad->town = "Thornbury";
        $ad->postcode = 3071;
        $ad->phone = "0400000016";
        $ad->email = User::where('name', 'Peter Parker')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.76';
        $ad->longitude = '145.007';
        $ad->save();
        // 69   
        $ad = new Advertisement();
        $ad->name = "Lance Custom Furniture";
        $ad->service = "Custom Furniture";
        $ad->quote = 0;
        $ad->body = "Unique funiture made to your liking";
        $ad->user_id = User::where('name', 'Qunintin Lance')->value('id');  
        $ad->town = "Coburg";
        $ad->postcode = 3058;
        $ad->phone = "0400000017";
        $ad->email = User::where('name', 'Qunintin Lance')->value('email');
        $ad->max_dist = 60; 
        $ad->latitude = '-37.741664';
        $ad->longitude = '144.962806';
        $ad->save();
        // 70
        $ad = new Advertisement();
        $ad->name = "Palmer Technologies";
        $ad->service = "Air Conditioning";
        $ad->quote = 0;
        $ad->body = "Technologies of the future";
        $ad->user_id = User::where('name', 'Ray Palmer')->value('id');  
        $ad->town = "Glen Waverly";
        $ad->postcode = 3150;
        $ad->phone = "0400000018";
        $ad->email = User::where('name', 'Ray Palmer')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.878543';
        $ad->longitude = '145.164812';
        $ad->save();
        // 71   
        $ad = new Advertisement();
        $ad->name = "Palmer Technologies";
        $ad->service = "Antenna Services";
        $ad->quote = 0;
        $ad->body = "Technologies of the future";
        $ad->user_id = User::where('name', 'Ray Palmer')->value('id'); 
        $ad->town = "Glen Waverly";
        $ad->postcode = 3150;
        $ad->phone = "0400000018";
        $ad->email = User::where('name', 'Ray Palmer')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.878543';
        $ad->longitude = '145.164812';
        $ad->save();
        // 72
        $ad = new Advertisement();
        $ad->name = "Palmer Technologies";
        $ad->service = "Appliance Installation";
        $ad->quote = 0;
        $ad->body = "Technologies of the future";
        $ad->user_id = User::where('name', 'Ray Palmer')->value('id'); 
        $ad->town = "Glen Waverly";
        $ad->postcode = 3150;
        $ad->phone = "0400000018";
        $ad->email = User::where('name', 'Ray Palmer')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.878543';
        $ad->longitude = '145.164812';
        $ad->save();
        // 73
        $ad = new Advertisement();
        $ad->name = "Palmer Technologies";
        $ad->service = "Appliance Repairs";
        $ad->quote = 0;
        $ad->body = "Technologies of the future";
        $ad->user_id = User::where('name', 'Ray Palmer')->value('id');
        $ad->town = "Glen Waverly";
        $ad->postcode = 3150;
        $ad->phone = "0400000018";
        $ad->email = User::where('name', 'Ray Palmer')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.878543';
        $ad->longitude = '145.164812';
        $ad->save();
        // 74
        $ad = new Advertisement();
        $ad->name = "Palmer Technologies";
        $ad->service = "Electricians";
        $ad->quote = 0;
        $ad->body = "Technologies of the future";
        $ad->user_id = User::where('name', 'Ray Palmer')->value('id');
        $ad->town = "Glen Waverly";
        $ad->postcode = 3150;
        $ad->phone = "0400000018";
        $ad->email = User::where('name', 'Ray Palmer')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.878543';
        $ad->longitude = '145.164812';
        $ad->save();
        // 75
        $ad = new Advertisement();
        $ad->name = "Palmer Technologies";
        $ad->service = "Heaters";
        $ad->quote = 0;
        $ad->body = "Technologies of the future";
        $ad->user_id = User::where('name', 'Ray Palmer')->value('id');
        $ad->town = "Glen Waverly";
        $ad->postcode = 3150;
        $ad->phone = "0400000018";
        $ad->email = User::where('name', 'Ray Palmer')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.878543';
        $ad->longitude = '145.164812';
        $ad->save();
        // 76
        $ad = new Advertisement();
        $ad->name = "Palmer Technologies";
        $ad->service = "Home Security";
        $ad->quote = 0;
        $ad->body = "Technologies of the future";
        $ad->user_id = User::where('name', 'Ray Palmer')->value('id'); 
        $ad->town = "Glen Waverly";
        $ad->postcode = 3150;
        $ad->phone = "0400000018";
        $ad->email = User::where('name', 'Ray Palmer')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.878543';
        $ad->longitude = '145.164812';
        $ad->save();
        // 77
        $ad = new Advertisement();
        $ad->name = "Palmer Technologies";
        $ad->service = "Home Theater";
        $ad->quote = 0;
        $ad->body = "Technologies of the future";
        $ad->user_id = User::where('name', 'Ray Palmer')->value('id'); 
        $ad->town = "Glen Waverly";
        $ad->postcode = 3150;
        $ad->phone = "0400000018";
        $ad->email = User::where('name', 'Ray Palmer')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.878543';
        $ad->longitude = '145.164812';
        $ad->save();
        // 78
        $ad = new Advertisement();
        $ad->name = "Palmer Technologies";
        $ad->service = "Hot Water System";
        $ad->quote = 0;
        $ad->body = "Technologies of the future";
        $ad->user_id = User::where('name', 'Ray Palmer')->value('id');
        $ad->town = "Glen Waverly";
        $ad->postcode = 3150;
        $ad->phone = "0400000018";
        $ad->email = User::where('name', 'Ray Palmer')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.878543';
        $ad->longitude = '145.164812';
        $ad->save();
        // 79
        $ad = new Advertisement();
        $ad->name = "Palmer Technologies";
        $ad->service = "Lighting";
        $ad->quote = 0;
        $ad->body = "Technologies of the future";
        $ad->user_id = User::where('name', 'Ray Palmer')->value('id'); 
        $ad->town = "Glen Waverly";
        $ad->postcode = 3150;
        $ad->phone = "0400000018";
        $ad->email = User::where('name', 'Ray Palmer')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.878543';
        $ad->longitude = '145.164812';
        $ad->save();
        // 80
        $ad = new Advertisement();
        $ad->name = "Palmer Technologies";
        $ad->service = "Solar Panels";
        $ad->quote = 0;
        $ad->body = "Technologies of the future";
        $ad->user_id = User::where('name', 'Ray Palmer')->value('id');  
        $ad->town = "Glen Waverly";
        $ad->postcode = 3150;
        $ad->phone = "0400000018";
        $ad->email = User::where('name', 'Ray Palmer')->value('email');
        $ad->max_dist = 50; 
        $ad->latitude = '-37.878543';
        $ad->longitude = '145.164812';
        $ad->save();
        // 81
        $ad = new Advertisement();
        $ad->name = "Kyle's Cleaning Services";
        $ad->service = "Window Cleaning";
        $ad->quote = 0;
        $ad->body = "We keep everything neat and tidy";
        $ad->user_id = User::where('name', 'Selina Kyle')->value('id'); 
        $ad->town = "Chadstone";
        $ad->postcode = 3148;
        $ad->phone = "0400000019";
        $ad->email = User::where('name', 'Selina Kyle')->value('email');
        $ad->max_dist = 25; 
        $ad->latitude = '-37.887876';
        $ad->longitude = '145.095203';
        $ad->save();
        // 82
        $ad = new Advertisement();
        $ad->name = "Kyle's Cleaning Services";
        $ad->service = "Rubish Removal";
        $ad->quote = 0;
        $ad->body = "We keep everything neat and tidy";
        $ad->user_id = User::where('name', 'Selina Kyle')->value('id'); 
        $ad->town = "Chadstone";
        $ad->postcode = 3148;
        $ad->phone = "0400000019";
        $ad->email = User::where('name', 'Selina Kyle')->value('email');
        $ad->max_dist = 25; 
        $ad->latitude = '-37.887876';
        $ad->longitude = '145.095203';
        $ad->save();
        // 83
        $ad = new Advertisement();
        $ad->name = "Kyle's Cleaning Services";
        $ad->service = "Skips";
        $ad->quote = 0;
        $ad->body = "We keep everything neat and tidy";
        $ad->user_id = User::where('name', 'Selina Kyle')->value('id');
        $ad->town = "Chadstone";
        $ad->postcode = 3148;
        $ad->phone = "0400000019";
        $ad->email = User::where('name', 'Selina Kyle')->value('email');
        $ad->max_dist = 25; 
        $ad->latitude = '-37.887876';
        $ad->longitude = '145.095203';
        $ad->save();
        // 84
        $ad = new Advertisement();
        $ad->name = "Kyle's Cleaning Services";
        $ad->service = "House Cleaning";
        $ad->quote = 0;
        $ad->body = "We keep everything neat and tidy";
        $ad->user_id = User::where('name', 'Selina Kyle')->value('id');  
        $ad->town = "Chadstone";
        $ad->postcode = 3148;
        $ad->phone = "0400000019";
        $ad->email = User::where('name', 'Selina Kyle')->value('email');
        $ad->max_dist = 25; 
        $ad->latitude = '-37.887876';
        $ad->longitude = '145.095203';
        $ad->save();
        // 85
        $ad = new Advertisement();
        $ad->name = "Kyle's Cleaning Services";
        $ad->service = "Commercial Cleaning";
        $ad->quote = 0;
        $ad->body = "We keep everything neat and tidy";
        $ad->user_id = User::where('name', 'Selina Kyle')->value('id'); 
        $ad->town = "Chadstone";
        $ad->postcode = 3148;
        $ad->phone = "0400000019";
        $ad->email = User::where('name', 'Selina Kyle')->value('email');
        $ad->max_dist = 25; 
        $ad->latitude = '-37.887876';
        $ad->longitude = '145.095203';
        $ad->save();
        // 86
        $ad = new Advertisement();
        $ad->name = "Kyle's Cleaning Services";
        $ad->service = "Carpet Cleaning";
        $ad->quote = 0;
        $ad->body = "We keep everything neat and tidy";
        $ad->user_id = User::where('name', 'Selina Kyle')->value('id'); 
        $ad->town = "Chadstone";
        $ad->postcode = 3148;
        $ad->phone = "0400000019";
        $ad->email = User::where('name', 'Selina Kyle')->value('email');
        $ad->max_dist = 25; 
        $ad->latitude = '-37.887876';
        $ad->longitude = '145.095203';
        $ad->save();
        // 87
        $ad = new Advertisement();
        $ad->name = "Thor's electrical service";
        $ad->service = "Antenna Services";
        $ad->quote = 100;
        $ad->body = "Powering your homes";
        $ad->user_id = User::where('name', 'Thor Odinson')->value('id');  
        $ad->town = "Malvern";
        $ad->postcode = 3144;
        $ad->phone = "0400000020";
        $ad->email = User::where('name', 'Thor Odinson')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.857';
        $ad->longitude = '145.036';
        $ad->save();
        // 88
        $ad = new Advertisement();
        $ad->name = "Thor's electrical service";
        $ad->service = "Electricians";
        $ad->quote = 100;
        $ad->body = "Powering your homes";
        $ad->user_id = User::where('name', 'Thor Odinson')->value('id'); 
        $ad->town = "Malvern";
        $ad->postcode = 3144;
        $ad->phone = "0400000020";
        $ad->email = User::where('name', 'Thor Odinson')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.857';
        $ad->longitude = '145.036';
        $ad->save();
        // 89
        $ad = new Advertisement();
        $ad->name = "Thor's electrical service";
        $ad->service = "Air Conditioning";
        $ad->quote = 100;
        $ad->body = "Powering your homes";
        $ad->user_id = User::where('name', 'Thor Odinson')->value('id'); 
        $ad->town = "Malvern";
        $ad->postcode = 3144;
        $ad->phone = "0400000020";
        $ad->email = User::where('name', 'Thor Odinson')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.857';
        $ad->longitude = '145.036';
        $ad->save();
        // 90
        $ad = new Advertisement();
        $ad->name = "Thor's electrical service";
        $ad->service = "Lighting";
        $ad->quote = 100;
        $ad->body = "Powering your homes";
        $ad->user_id = User::where('name', 'Thor Odinson')->value('id'); 
        $ad->town = "Malvern";
        $ad->postcode = 3144;
        $ad->phone = "0400000020";
        $ad->email = User::where('name', 'Thor Odinson')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.857';
        $ad->longitude = '145.036';
        $ad->save();
        // 91
        $ad = new Advertisement();
        $ad->name = "Savage Removalists";
        $ad->service = "Skips";
        $ad->quote = 30;
        $ad->body = "We want your unwated stuff";
        $ad->user_id = User::where('name', 'Vandal Savage')->value('id'); 
        $ad->town = "Bundoora";
        $ad->postcode = 3083;
        $ad->phone = "0400000021";
        $ad->email = User::where('name', 'Vandal Savage')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.69706';
        $ad->longitude = '145.059002';
        $ad->save();
        // 92
        $ad = new Advertisement();
        $ad->name = "Savage Removalists";
        $ad->service = "Removalists";
        $ad->quote = 30;
        $ad->body = "We want your unwated stuff";
        $ad->user_id = User::where('name', 'Vandal Savage')->value('id');  
        $ad->town = "Bundoora";
        $ad->postcode = 3083;
        $ad->phone = "0400000021";
        $ad->email = User::where('name', 'Vandal Savage')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.69706';
        $ad->longitude = '145.059002';
        $ad->save();
        // 93
        $ad = new Advertisement();
        $ad->name = "Savage Removalists";
        $ad->service = "Rubish Removal";
        $ad->quote = 30;
        $ad->body = "We want your unwated stuff";
        $ad->user_id = User::where('name', 'Vandal Savage')->value('id'); 
        $ad->town = "Bundoora";
        $ad->postcode = 3083;
        $ad->phone = "0400000021";
        $ad->email = User::where('name', 'Vandal Savage')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.69706';
        $ad->longitude = '145.059002';
        $ad->save();
        // 94
        $ad = new Advertisement();
        $ad->name = "West Plumbers";
        $ad->service = "Plumbers";
        $ad->quote = 0;
        $ad->body = "We service your pipes";
        $ad->user_id = User::where('name', 'Wally West')->value('id');  
        $ad->town = "Keilor East";
        $ad->postcode = 3033;
        $ad->phone = "0400000022";
        $ad->email = User::where('name', 'Wally West')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.741667';
        $ad->longitude = '144.863056';
        $ad->save();
        // 95
        $ad = new Advertisement();
        $ad->name = "Zantanna's Security";
        $ad->service = "Locksmith";
        $ad->quote = 0;
        $ad->body = "We keep you secure";
        $ad->user_id = User::where('name', 'Zantanna Zatara')->value('id'); 
        $ad->town = "Keilor East";
        $ad->postcode = 3033;
        $ad->phone = "0400000023";
        $ad->email = User::where('name', 'Zantanna Zatara')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.741667';
        $ad->longitude = '144.863056';
        $ad->save();
        // 96
        $ad = new Advertisement();
        $ad->name = "Zantanna's Security";
        $ad->service = "Security Screen Doors";
        $ad->quote = 0;
        $ad->body = "We keep you secure";
        $ad->user_id = User::where('name', 'Zantanna Zatara')->value('id');  
        $ad->town = "Keilor East";
        $ad->postcode = 3033;
        $ad->phone = "0400000023";
        $ad->email = User::where('name', 'Zantanna Zatara')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.741667';
        $ad->longitude = '144.863056';
        $ad->save();
        // 97
        $ad = new Advertisement();
        $ad->name = "Zantanna's Security";
        $ad->service = "Home Security";
        $ad->quote = 0;
        $ad->body = "We keep you secure";
        $ad->user_id = User::where('name', 'Zantanna Zatara')->value('id');
        $ad->town = "Keilor East";
        $ad->postcode = 3033;
        $ad->phone = "0400000023";
        $ad->email = User::where('name', 'Zantanna Zatara')->value('email');
        $ad->max_dist = 40; 
        $ad->latitude = '-37.741667';
        $ad->longitude = '144.863056';
        $ad->save();
    }
}
